# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_env.ipynb.

# %% auto 0
__all__ = ['TextRLEnv']

# %% ../nbs/04_env.ipynb 2
# from textrl import TextRLEnv, TextRLActor
import torch
import gymnasium as gym

# %% ../nbs/04_env.ipynb 3
class TextRLEnv(gym.Env):
    def __init__(self, model, tokenizer, observation_input=[], max_length=100):
        vocabs = list(dict(sorted(tokenizer.vocab.items(), key=lambda item: item[1])).keys())
        
        self.action_space = gym.spaces.Discrete(len(vocabs))
        self.actions = vocabs
        self.model = model
        
        # TODO: what is this
        self.env_max_length = max_length
        self.tokenizer = tokenizer
        # TODO: what is this
        self.observation_space = observation_input
        self.target_table = {}
        self.input_item = [""]
        self.predicted = []
        
        self.reset()
    
    def reset(self): pass
