# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_reward_model.ipynb.

# %% auto 0
__all__ = ['RewardModel', 'RewardLoss']

# %% ../nbs/03_reward_model.ipynb 3
import torch
from torch import nn
import torch.nn.functional as F
from transformers import AutoModel, AutoTokenizer
from einops import rearrange

from .utils import load_yaml

# %% ../nbs/03_reward_model.ipynb 6
class RewardModel(nn.Module):
    def __init__(self, checkpoint: str, dropout: float = 0.1):
        super().__init__()
        self.tokenizer = AutoTokenizer.from_pretrained(checkpoint)
        self.model = AutoModel.from_pretrained(checkpoint)
        
        config = self.model.config
        n_embed = config.n_embd
        
        # custom head
        self.dropout = nn.Dropout(dropout)
        self.reward_head = nn.Linear(n_embed, 1)
        
    def forward(self, input_ids: torch.Tensor, attention_mask: torch.Tensor):
        last_hidden_state = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
        ).last_hidden_state
        
        output = self.dropout(last_hidden_state)
        output = self.reward_head(output)
                
        # output = rearrange(output, 'b 1 t 1 -> b t')
        # for eacb item in the batch
        # choose the hidden state of the last token as a reward!
        reward_scalar = output[:, -1, 0]
        
        return reward_scalar

# %% ../nbs/03_reward_model.ipynb 10
class RewardLoss(nn.Module):
    def forward(self, chosen_reward: torch.Tensor, rejected_rewards: torch.Tensor):
        assert len(chosen_reward) == len(rejected_rewards)
        batch_size = len(chosen_reward)
        
        prob = F.sigmoid(chosen_reward - rejected_rewards)
        return -prob.mean() / batch_size
